In [1]:
import sys
import numpy as np
print("=" * 60)
print("VERIFICACIÓN DEL ENTORNO DE TRABAJO")
print("=" * 60)
print(f"\nPython: {sys.version}")
print(f"Ubicación: {sys.executable}")
print(f"\nNumPy: {np.__version__}")
print(f"Ubicación: {np.__file__}")

VERIFICACIÓN DEL ENTORNO DE TRABAJO

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Ubicación: /usr/bin/python3

NumPy: 2.0.2
Ubicación: /usr/local/lib/python3.12/dist-packages/numpy/__init__.py


In [2]:
# Crear un arreglo simple
arr = np.array([1, 2, 3, 4, 5])
print("\nARREGLO CREADO:")
print(f"Contenido: {arr}")
print(f"Tipo: {type(arr)}")
print(f"Forma: {arr.shape}")
print(f"Tipo de datos: {arr.dtype}")
print("\nOPERACIONES BÁSICAS:")
print(f"Suma: {np.sum(arr)}")
print(f"Media: {np.mean(arr)}")
print(f"Desviación estándar: {np.std(arr)}")
print(f"Mínimo: {np.min(arr)}")
print(f"Máximo: {np.max(arr)}")


ARREGLO CREADO:
Contenido: [1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>
Forma: (5,)
Tipo de datos: int64

OPERACIONES BÁSICAS:
Suma: 15
Media: 3.0
Desviación estándar: 1.4142135623730951
Mínimo: 1
Máximo: 5


In [5]:
import numpy as np
# Crear un escalar
escalar = np.array(42)
# escalar = np.array([42])
print(escalar)
print(f"Dimensiones: {escalar.ndim}")
print(f"Forma: {escalar.shape}")

42
Dimensiones: 0
Forma: ()


In [6]:
# Desde una lista
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)
print(f"Tipo: {type(arr1d)}")
print(f"Dimensiones: {arr1d.ndim}")
print(f"Forma: {arr1d.shape}")
print(f"Tamaño: {arr1d.size}")

[1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>
Dimensiones: 1
Forma: (5,)
Tamaño: 5


In [7]:
# NumPy acepta tanto listas como tuplas
arr_tupla = np.array((10, 20, 30, 40))
print(arr_tupla)

[10 20 30 40]


In [9]:
# NumPy acepta tanto listas como tuplas
arr_tupla = np.array((10,))
print(arr_tupla)

[10]


In [10]:
# Crear una matriz 3x3
arr2d = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9, 10]])
print(arr2d)
print(f"Dimensiones: {arr2d.ndim}")
print(f"Forma: {arr2d.shape}")
print(f"Tamaño total: {arr2d.size}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensiones: 2
Forma: (3, 3)
Tamaño total: 9
