In [2]:
import sys
import numpy as np
print("=" * 60)
print("VERIFICACIÓN DEL ENTORNO DE TRABAJO")
print("=" * 60)
print(f"\nPython: {sys.version}")
print(f"Ubicación: {sys.executable}")
print(f"\nNumPy: {np.__version__}")
print(f"Ubicación: {np.__file__}")

VERIFICACIÓN DEL ENTORNO DE TRABAJO

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Ubicación: /usr/bin/python3

NumPy: 2.0.2
Ubicación: /usr/local/lib/python3.12/dist-packages/numpy/__init__.py


In [ ]:
# Crear un arreglo simple
arr = np.array([1, 2, 3, 4, 5])
print("\nARREGLO CREADO:")
print(f"Contenido: {arr}")
print(f"Tipo: {type(arr)}")
print(f"Forma: {arr.shape}")
print(f"Tipo de datos: {arr.dtype}")
print("\nOPERACIONES BÁSICAS:")
print(f"Suma: {np.sum(arr)}")
print(f"Media: {np.mean(arr)}")
print(f"Desviación estándar: {np.std(arr)}")
print(f"Mínimo: {np.min(arr)}")
print(f"Máximo: {np.max(arr)}")


ARREGLO CREADO:
Contenido: [1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>
Forma: (5,)
Tipo de datos: int64

OPERACIONES BÁSICAS:
Suma: 15
Media: 3.0
Desviación estándar: 1.4142135623730951
Mínimo: 1
Máximo: 5


In [ ]:
import numpy as np
# Crear un escalar
escalar = np.array(42)
# escalar = np.array([42])
print(escalar)
print(f"Dimensiones: {escalar.ndim}")
print(f"Forma: {escalar.shape}")

42
Dimensiones: 0
Forma: ()


In [ ]:
# Desde una lista
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)
print(f"Tipo: {type(arr1d)}")
print(f"Dimensiones: {arr1d.ndim}")
print(f"Forma: {arr1d.shape}")
print(f"Tamaño: {arr1d.size}")

[1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>
Dimensiones: 1
Forma: (5,)
Tamaño: 5


In [ ]:
# NumPy acepta tanto listas como tuplas
arr_tupla = np.array((10, 20, 30, 40))
print(arr_tupla)

[10 20 30 40]


In [ ]:
# NumPy acepta tanto listas como tuplas
arr_tupla = np.array((10,))
print(arr_tupla)

[10]


In [9]:
# Crear una matriz 3x3
arr2d = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(arr2d)
print(f"Dimensiones: {arr2d.ndim}")
print(f"Forma: {arr2d.shape}")
print(f"Tamaño total: {arr2d.size}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensiones: 2
Forma: (3, 3)
Tamaño total: 9


In [10]:
# Arreglo 3-D (2x2x2)
arr3d = np.array([[[1, 2], [3, 4]],
[[5, 6], [7, 8]]])
print(arr3d)
print(f"Dimensiones: {arr3d.ndim}")
print(f"Forma: {arr3d.shape}")

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensiones: 3
Forma: (2, 2, 2)


In [11]:
# NumPy infiere int64
arr_int = np.array([1, 2, 3])
print(f"Tipo inferido: {arr_int.dtype}")

Tipo inferido: int64


In [12]:
# NumPy infiere float64
arr_float = np.array([1.0, 2.0, 3.0])
print(f"Tipo inferido: {arr_float.dtype}")

Tipo inferido: float64


In [13]:
# Especificar dtype explícitamente
arr_especifico = np.array([1, 2, 3], dtype=np.float32)
print(f"Tipo especificado: {arr_especifico.dtype}")

Tipo especificado: float32


In [16]:
# Especificar dtype explícitamente
arr_especifico = np.array([1.3, 2.5, 3.8], dtype=np.int64)
print(arr_especifico)
print(f"Tipo especificado: {arr_especifico.dtype}")

[1 2 3]
Tipo especificado: int64


In [20]:
# Arreglo 1-D de 5 ceros
zeros_1d = np.zeros(5)
print(zeros_1d)
print("="*30)
# Matriz 3x4 de ceros
zeros_2d = np.zeros((3, 4))
print(zeros_2d)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
# Matriz 2x3 de unos
ones_2d = np.ones((2, 3))
print(ones_2d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
# Matriz 2x2 llena de 7
full_arr = np.full((2, 2), 7)
print(full_arr)

[[7 7]
 [7 7]]


In [24]:
# Arreglo vacío de 3 elementos
empty_arr = np.empty(8)
print(empty_arr) # Valores aleatorios

[3.89744044e-315 0.00000000e+000 3.91221905e-315 3.91221905e-315
 4.94065646e-324 3.91221937e-315 3.91222147e-315 1.18575755e-322]


In [25]:
# Matriz identidad 3x3
identidad = np.eye(3)
print(identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# Del 0 al 9
arange1 = np.arange(10)
print(arange1)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
# Del 2 al 9
arange2 = np.arange(2, 10)
print(arange2)

[2 3 4 5 6 7 8 9]


In [28]:
# Del 0 al 20 de 2 en 2
arange3 = np.arange(0, 21, 2)
print(arange3)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [31]:
# 5 valores entre 0 y 10 (incluye ambos extremos)
linspace_arr = np.linspace(0, 10, num=6)
print(linspace_arr)

[ 0.  2.  4.  6.  8. 10.]


In [32]:
arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print(f"Forma: {arr.shape}")
# Forma: (3, 4) -> 3 filas, 4 columnas

Forma: (3, 4)


In [33]:
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2], [3, 4]])
arr_3d = np.array([[[1, 2]], [[3, 4]]])
print(f"1-D: {arr_1d.ndim} dimensiones")
print(f"2-D: {arr_2d.ndim} dimensiones")
print(f"3-D: {arr_3d.ndim} dimensiones")

1-D: 1 dimensiones
2-D: 2 dimensiones
3-D: 3 dimensiones


In [34]:
mat = [ [1,2,3],[4,5,6],[7,8,9,10]]
print( mat )

[[1, 2, 3], [4, 5, 6], [7, 8, 9, 10]]


In [37]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Forma: {arr.shape}")
print(f"Tamaño: {arr.size}")
# size = 2 × 3 = 6 elementos

Forma: (2, 3)
Tamaño: 6


In [38]:
arr_int = np.array([1, 2, 3])
arr_float = np.array([1.5, 2.5, 3.5])
print(f"Tipo de arr_int: {arr_int.dtype}")
print(f"Tipo de arr_float: {arr_float.dtype}")

Tipo de arr_int: int64
Tipo de arr_float: float64


In [40]:
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
arr_float64 = np.array([1.0, 2.0], dtype=np.float64)
print(f"int32: {arr_int32.itemsize} bytes")
print(f"float64: {arr_float64.itemsize} bytes")

int32: 4 bytes
float64: 8 bytes


In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
print(f"Tamaño: {arr.size} elementos")
print(f"Item size: {arr.itemsize} bytes")
print(f"Total bytes: {arr.nbytes} bytes")
# nbytes = size × itemsize = 6 × 4 = 24 bytes

Tamaño: 6 elementos
Item size: 4 bytes
Total bytes: 24 bytes


In [43]:
# Crear diferentes tipos de arreglos
print("=" * 60)
print("EJEMPLO INTEGRADOR: CREACIÓN Y EXPLORACIÓN DE ARREGLOS")
print("=" * 60)

# 1. Arreglo 1-D desde lista
arr1d = np.array([10, 20, 30, 40, 50])
print("\n1. ARREGLO 1-D:")
print(arr1d)
print(f" Tipo: {type(arr1d)}")
print(f" Shape: {arr1d.shape}")
print(f" Ndim: {arr1d.ndim}")
print(f" Size: {arr1d.size}")
print(f" Dtype: {arr1d.dtype}")
# 2. Matriz 2-D
matriz = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print("\n2. MATRIZ 2-D:")
print(matriz)
print(f" Shape: {matriz.shape} (3 filas, 4 columnas)")
print(f" Ndim: {matriz.ndim}")
print(f" Size: {matriz.size}")
# 3. Arreglos con funciones especializadas
print("\n3. ARREGLOS CON FUNCIONES ESPECIALIZADAS:")
zeros = np.zeros((2, 3))
print(" Zeros (2x3):")
print(zeros)
ones = np.ones((2, 2), dtype=np.int32)
print("\n Ones (2x2, int32):")
print(ones)
identidad = np.eye(3)
print("\n Identidad (3x3):")
print(identidad)
rango = np.arange(0, 20, 3)
print("\n Arange (0 a 20, paso 3):")
print(rango)

lineal = np.linspace(0, 1, 6)
print("\n Linspace (0 a 1, 6 valores):")
print(lineal)
# 4. Comparación de memoria
arr_int32 = np.array([1, 2, 3, 4, 5], dtype=np.int32)
arr_int64 = np.array([1, 2, 3, 4, 5], dtype=np.int64)
print("\n4. COMPARACIÓN DE MEMORIA:")
print(f" int32: {arr_int32.itemsize} bytes/elemento, "
f"{arr_int32.nbytes} bytes total")
print(f" int64: {arr_int64.itemsize} bytes/elemento, "
f"{arr_int64.nbytes} bytes total")

EJEMPLO INTEGRADOR: CREACIÓN Y EXPLORACIÓN DE ARREGLOS

1. ARREGLO 1-D:
[10 20 30 40 50]
 Tipo: <class 'numpy.ndarray'>
 Shape: (5,)
 Ndim: 1
 Size: 5
 Dtype: int64

2. MATRIZ 2-D:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 Shape: (3, 4) (3 filas, 4 columnas)
 Ndim: 2
 Size: 12

3. ARREGLOS CON FUNCIONES ESPECIALIZADAS:
 Zeros (2x3):
[[0. 0. 0.]
 [0. 0. 0.]]

 Ones (2x2, int32):
[[1 1]
 [1 1]]

 Identidad (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Arange (0 a 20, paso 3):
[ 0  3  6  9 12 15 18]

 Linspace (0 a 1, 6 valores):
[0.  0.2 0.4 0.6 0.8 1. ]

4. COMPARACIÓN DE MEMORIA:
 int32: 4 bytes/elemento, 20 bytes total
 int64: 8 bytes/elemento, 40 bytes total


In [47]:
arr = np.array([[1, 2], [3, 4]])
for elemento in arr:
  print(elemento, end=', ')
# Salida: [1 2], [3 4],

[1 2], [3 4], 

In [48]:
arr = np.array([[1, 2], [3, 4]])
for elemento in arr.flat:
  print(elemento, end=', ')
# Salida: 1 2 3 4

1, 2, 3, 4, 

## 5.3 Métodos de Transformación de Forma

In [4]:
arr1d = np.arange(12)
print(f'Original: {arr1d}')

arr2d = arr1d.reshape(3, 4)
print('\nReshape a 3x4:')
print(arr2d)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshape a 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Uso de -1: NumPy (2025) puede inferir automáticamente una dimensión:

In [7]:
arr_auto = arr1d.reshape(-1, 3) # Infiere 4 columnas
print(arr_auto.shape) # (3, 4)
print(arr_auto)

(4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#5.3.2 flatten() - Aplanar a 1-D
Retorna una copia del arreglo colapsada a una dimensión (NumPy, 2025):

In [15]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
plano = matriz.flatten()
print(plano) # [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [10]:
# Es una copia independiente
plano[0] = 999
print(plano) # [999 2 3 4 5 6]
print(matriz[0, 0]) # 1 (no cambió)

[999   2   3   4   5   6]
1


#5.3.3 ravel() - Aplanar (Vista)
Según la documentación oficial de NumPy (2025), ravel() retorna un array
unidimensional (1D) aplanado que contiene los elementos del array original.

Ejemplo 1: Orden por defecto

In [18]:
matriz = np.array([[1, 2], [3, 4]])
plano = matriz.ravel()
plano2 = np.ravel(matriz)
print(plano) # [1, 2, 3, 4]
print(plano2) # [1, 2, 3, 4]
# Es una vista, modificar afecta al original
print("="*15)
plano[0] = 999
print(plano) # [999, 2, 3 4]
print(matriz) # [[999 2] [ 3 4]]

[1 2 3 4]
[1 2 3 4]
[999   2   3   4]
[[999   2]
 [  3   4]]


In [13]:
# Orden 'F' (por columnas)
ravel_f = matriz.ravel(order='F')
print(ravel_f)
# [999 3 2 4]
# Lee: columna1 completa, luego columna2, luego columna3

[999   3   2   4]


#5.4 transpose() - Transposición General
Más general que .T para arreglos N-D (NumPy, 2025):
Según la documentación oficial de NumPy (2025), transpose() retorna un array con
los ejes (dimensiones) permutados. En términos simples, intercambia filas por
columnas en matrices 2D, pero su poder real se extiende a arrays de cualquier número
de dimensiones.

In [19]:
# Matriz 2x3
matriz = np.array([[1, 2, 3],
[4, 5, 6]])
print("Matriz original:")
print(matriz)
print(f"Shape: {matriz.shape}")

Matriz original:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [20]:
# Transponer
transpuesta = matriz.transpose()
# o simplemente: matriz.T
print("\nMatriz transpuesta:")
print(transpuesta)
print(f"Shape: {transpuesta.shape}")


Matriz transpuesta:
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)


##Las Tres Formas de Transponer

In [21]:
a = np.array([[1, 2, 3],
[4, 5, 6]])
# Forma 1: Método transpose()
t1 = a.transpose()
print(t1)

[[1 4]
 [2 5]
 [3 6]]


In [22]:
# Forma 2: Atributo .T (más común y conciso)
t2 = a.T
print(t2)

[[1 4]
 [2 5]
 [3 6]]


In [23]:
# Forma 3: Función np.transpose()
t3 = np.transpose(a)
print(t3)

[[1 4]
 [2 5]
 [3 6]]


In [24]:
# Todas son equivalentes
print(np.array_equal(t1, t2)) # True
print(np.array_equal(t1, t3)) # True

True
True


#5.5 Métodos Matemáticos y Estadísticos
Según NumPy (2025), estos métodos aceptan el parámetro axis para operar sobre dimensiones específicas.

##5.5.1 sum() - Suma de Elementos

In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
print(f'Suma total: {arr.sum()}') # 45
print(f'Por columnas: {arr.sum(axis=0)}') # [12 15 18]
print(f'Por filas: {arr.sum(axis=1)}') # [ 6 15 24]

Suma total: 45
Por columnas: [12 15 18]
Por filas: [ 6 15 24]


##5.5.2 mean(), median(), std(), var() - Estadísticas

In [26]:
datos = np.array([10, 20, 20, 30, 40, 50, 1000])
print(f'Media: {np.mean(datos):.2f}') # 30.0
print(f'Mediana: {np.median(datos):.2f}') # 30.0
print(f'Desv. estándar: {datos.std():.2f}')
print(f'Varianza: {datos.var():.2f}')

Media: 167.14
Mediana: 30.00
Desv. estándar: 340.24
Varianza: 115763.27


##5.5.3 min(), max(), argmin(), argmax()

In [27]:
arr = np.array([[5, 2, 8], [1, 9, 3]])
print(f'Mínimo: {arr.min()}') # 1
print(f'Máximo: {arr.max()}') # 9
print(f'Índice del mín: {arr.argmin()}') # 3
print(f'Índice del máx: {arr.argmax()}') # 4

Mínimo: 1
Máximo: 9
Índice del mín: 3
Índice del máx: 4


##5.5.4 cumsum(), cumprod() – Acumulativos

In [30]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.cumsum()) # [ 1 3 6 10 15]
print(arr.cumprod()) # [ 1 2 6 24 120]

[ 1  3  6 10 15]
[  1   2   6  24 120]


#5.6 . Métodos de Ordenamiento

##5.6.1 sort() - Ordenar In-Place
Ordena el arreglo in-place (NumPy, 2025).

In [31]:
arr = np.array([3, 1, 4, 1, 5])
arr.sort()
print(arr) # [1 1 3 4 5]

[1 1 3 4 5]


##5.6.2 argsort() - Índices de Ordenamiento

In [32]:
arr = np.array([30, 10, 20, 50, 40])
indices = arr.argsort()
print(f'Índices: {indices}') # [1 2 0 4 3]
print(f'Ordenado: {arr[indices]}') # [10 20 30 40 50]
print(f"Origina: {arr}")

Índices: [1 2 0 4 3]
Ordenado: [10 20 30 40 50]
Origina: [30 10 20 50 40]


#5.7 Métodos de Copia

##5.7.1 copy() - Copia Profunda

In [33]:
original = np.array([1, 2, 3])
copia = original.copy()
copia[0] = 999
print(f'Original: {original}') # [1 2 3]
print(f'Copia: {copia}') # [999 2 3]

Original: [1 2 3]
Copia: [999   2   3]


##5.7.2 view() – Vista

In [35]:
original = np.array([1, 2, 3])
vista = original.view()
vista[0] = 999
print(f'Original: {original}') # [999 2 3]
print(f'Vista: {vista}') # [999 2 3]

Original: [999   2   3]
Vista: [999   2   3]


#5.8 Métodos de Conversión

##5.8.1 astype() - Conversión de Tipo

In [36]:
arr_float = np.array([1.5, 2.3, 3.9])
arr_int = arr_float.astype(np.int32)
print(f'Float: {arr_float}, dtype: {arr_float.dtype}')
print(f'Int: {arr_int}, dtype: {arr_int.dtype}')

Float: [1.5 2.3 3.9], dtype: float64
Int: [1 2 3], dtype: int32


Truco para hacer redondeo.

In [37]:
arr_float = np.array([1.7, 2.3, 3.9])

arr_float_round = np.round(arr_float)
print(arr_float_round)
print("="*15)

# Redondea primero y luego convierte a entero
arr_int = np.round(arr_float).astype(np.int32)

print(f'Float: {arr_float}, dtype: {arr_float.dtype}')
print(f'Int: {arr_int}, dtype: {arr_int.dtype}')
# Salida de Int: [2 2 4], dtype: int32

[2. 2. 4.]
Float: [1.7 2.3 3.9], dtype: float64
Int: [2 2 4], dtype: int32


##5.8.2 tolist() - A Lista Python

In [38]:
arr = np.array([[1, 2], [3, 4]])
lista = arr.tolist()
print(type(arr))
print(type(lista)) # <class 'list'>

<class 'numpy.ndarray'>
<class 'list'>
